name: Deploy to Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: firstwebdeploy          # Senin Proje ID'n
  REGION: europe-west3                # Senin seçtiğin bölge
  REPO_NAME: web-repo                 # Senin oluşturduğun depo adı
  SERVICE_NAME: my-node-app           # Cloud Run'da görünecek servis adı

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Google Cloud'a Giriş Yap
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      # Docker'ı Google Cloud için ayarla
      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      # İmajı Oluştur ve Yükle (Build & Push)
      - name: Build and Push Container
        run: |
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

      # Cloud Run'a Deploy Et
      - name: Deploy to Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v2'
        with:
          service: ${{ env.SERVICE_NAME }}
          image: ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
          region: ${{ env.REGION }}
          flags: '--allow-unauthenticated' # Herkesin erişebilmesi için

      - name: Show Output
        run: echo "Uygulama yayında ${{ steps.deploy.outputs.url }}"
